/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatabaseName = string;
export type Id = number;
export type Name = string;
export type Description = string;
export type CreatedAt = string;
export type Id1 = number;
export type Url = string | null;
export type InputType = string;
export type Filename = string | null;
export type Model = string;
export type Granularity = string;
export type SubmittedAt = string;
export type CompletedAt = string | null;
export type Error = string | null;
export type EntriesCount = number;
export type Duration = number | null;
export type SpeakersCount = number;
export type CreatedBy = string | null;
export type Transcriptions = TranscriptionSummary[];
export type AvailableTranscriptions = TranscriptionSummary[];
export type Id2 = number;
export type Name1 = string;
export type Description1 = string;
export type HasPhoto = boolean;
export type EntryCount = number;
export type TranscriptionCount = number;
export type Speakers = CollectionSpeakerStat[];
export type ResourceType = string;
export type Parent = string;
export type Child = string;
export type Features = string;
export type CanManage = boolean;
export type Available = boolean;

export interface CollectionDetailPageData {
  database_name: DatabaseName;
  collection: CollectionSummary;
  transcriptions?: Transcriptions;
  available_transcriptions?: AvailableTranscriptions;
  speakers?: Speakers;
  share?: ShareInfo | null;
  [k: string]: unknown;
}
export interface CollectionSummary {
  id: Id;
  name: Name;
  description?: Description;
  created_at?: CreatedAt;
  [k: string]: unknown;
}
export interface TranscriptionSummary {
  id: Id1;
  url?: Url;
  input_type?: InputType;
  filename?: Filename;
  model: Model;
  granularity: Granularity;
  submitted_at: SubmittedAt;
  completed_at?: CompletedAt;
  error?: Error;
  entries_count?: EntriesCount;
  duration?: Duration;
  speakers_count?: SpeakersCount;
  created_by?: CreatedBy;
  [k: string]: unknown;
}
export interface CollectionSpeakerStat {
  id: Id2;
  name: Name1;
  description?: Description1;
  has_photo?: HasPhoto;
  entry_count: EntryCount;
  transcription_count: TranscriptionCount;
  [k: string]: unknown;
}
export interface ShareInfo {
  resource_type: ResourceType;
  parent: Parent;
  child: Child;
  features?: Features;
  can_manage?: CanManage;
  available?: Available;
  [k: string]: unknown;
}
