/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatabaseName = string;
export type Id = number;
export type Name = string;
export type Description = string;
export type CreatedAt = string;
export type Collections = CollectionSummary[];

export interface NewTranscriptionPageData {
  database_name: DatabaseName;
  collections?: Collections;
  [k: string]: unknown;
}
export interface CollectionSummary {
  id: Id;
  name: Name;
  description?: Description;
  created_at?: CreatedAt;
  [k: string]: unknown;
}
