/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatabaseName = string;
export type Id = number;
export type Name = string;
export type Description = string;
export type CreatedAt = string;
export type Id1 = number;
export type Url = string | null;
export type InputType = string;
export type Filename = string | null;
export type Model = string;
export type Granularity = string;
export type SubmittedAt = string;
export type CompletedAt = string | null;
export type Error = string | null;
export type EntriesCount = number;
export type Duration = number | null;
export type SpeakersCount = number;
export type Transcriptions = TranscriptionSummary[];
export type Collections = CollectionWithTranscriptions[];
export type UncollectedTranscriptions = TranscriptionSummary[];

export interface ScribePageData {
  database_name: DatabaseName;
  collections?: Collections;
  uncollected_transcriptions?: UncollectedTranscriptions;
  [k: string]: unknown;
}
export interface CollectionWithTranscriptions {
  id: Id;
  name: Name;
  description?: Description;
  created_at?: CreatedAt;
  transcriptions?: Transcriptions;
  [k: string]: unknown;
}
export interface TranscriptionSummary {
  id: Id1;
  url?: Url;
  input_type?: InputType;
  filename?: Filename;
  model: Model;
  granularity: Granularity;
  submitted_at: SubmittedAt;
  completed_at?: CompletedAt;
  error?: Error;
  entries_count?: EntriesCount;
  duration?: Duration;
  speakers_count?: SpeakersCount;
  [k: string]: unknown;
}
