/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatabaseName = string;
export type Id = number;
export type Url = string | null;
export type InputType = string;
export type Filename = string | null;
export type Model = string;
export type Granularity = string;
export type SubmittedAt = string;
export type CompletedAt = string | null;
export type Error = string | null;
export type EntriesCount = number;
export type Duration = number | null;
export type SpeakersCount = number;
export type AudioUrl = string | null;
export type Id1 = number;
export type Start = number;
export type End = number;
export type SpeakerId = string | null;
export type Text = string;
export type OriginalSpeakerId = string | null;
export type OriginalText = string | null;
export type Entries = TranscriptionEntry[];
export type Id2 = number;
export type Name = string;
export type IsOriginal = boolean;
export type UsedInOtherTranscriptions = boolean;
export type Speakers = TranscriptionSpeaker[];
export type AllSpeakers = TranscriptionSpeaker[];
export type Id3 = number;
export type Operation = string;
export type Detail = string;
export type CreatedAt = string;
export type EntryId = number | null;
export type Edits = TranscriptionEdit[];
export type Id4 = number;
export type Name1 = string;
export type Description = string;
export type CreatedAt1 = string;
export type AllCollections = CollectionSummary[];

export interface TranscriptionDetailPageData {
  database_name: DatabaseName;
  transcription: TranscriptionSummary;
  audio_url?: AudioUrl;
  entries?: Entries;
  speakers?: Speakers;
  all_speakers?: AllSpeakers;
  edits?: Edits;
  collection?: CollectionSummary | null;
  all_collections?: AllCollections;
  [k: string]: unknown;
}
export interface TranscriptionSummary {
  id: Id;
  url?: Url;
  input_type?: InputType;
  filename?: Filename;
  model: Model;
  granularity: Granularity;
  submitted_at: SubmittedAt;
  completed_at?: CompletedAt;
  error?: Error;
  entries_count?: EntriesCount;
  duration?: Duration;
  speakers_count?: SpeakersCount;
  [k: string]: unknown;
}
export interface TranscriptionEntry {
  id: Id1;
  start: Start;
  end: End;
  speaker_id?: SpeakerId;
  text: Text;
  original_speaker_id?: OriginalSpeakerId;
  original_text?: OriginalText;
  [k: string]: unknown;
}
export interface TranscriptionSpeaker {
  id: Id2;
  name: Name;
  is_original?: IsOriginal;
  used_in_other_transcriptions?: UsedInOtherTranscriptions;
  [k: string]: unknown;
}
export interface TranscriptionEdit {
  id: Id3;
  operation: Operation;
  detail: Detail;
  created_at: CreatedAt;
  entry_id?: EntryId;
  [k: string]: unknown;
}
export interface CollectionSummary {
  id: Id4;
  name: Name1;
  description?: Description;
  created_at?: CreatedAt1;
  [k: string]: unknown;
}
